# Stage 1: Build
FROM golang:1.22.5-alpine AS build

WORKDIR /src

COPY . .

WORKDIR /src/cmd/consumer

RUN go mod download
RUN go build -o /bin/consumer

# Stage 2: Create the final image
FROM scratch

COPY --from=build /bin/consumer /bin/consumer

CMD ["/bin/consumer"]
